# See this guide for more settings:
#
# http://about.travis-ci.org/docs/user/build-configuration/

# See this guide for more settings:
#
# http://about.travis-ci.org/docs/user/build-configuration/

sudo: false
language: java
mvn: mvn2
script: mvn package
jdk:
  - oraclejdk8
notifications:
  email:
    - cch@transparencyrights.com
